Repository route06/actions, pull requests merged in 2024-06, with the labels that each got.

#33 maintenance: change section and add label for release.yml
  .github/release.yml
Labels: maintenance

#34 CodeQL workflow ignores deleted files
  .github/workflows/codeql.yml
Labels: bug

#35 Introduce actionlint workflow
  .github/workflows/gh_discussion_comment_to_slack.yml
  .github/workflows/my_release.yml
  .github/workflows/my_test.yml
  .github/workflows/notify_slack_on_ci_failed.yml
Labels: maintenance

#38 Refactor CI
  .github/workflows/add_assignee_to_pr.yml
  .github/workflows/my_setup_pr.yml
  .github/workflows/my_test.yml
Labels: maintenance

#41 Fix gh_discussion_comment_to_slack.yml
  .github/workflows/gh_discussion_comment_to_slack.yml
Labels: bug

#43 Fix gh_discussion_comment_to_slack.yml part2
  .github/workflows/gh_discussion_comment_to_slack.yml
Labels: bug

#44 fix missing permission for my_setup_pr.yml
  .github/workflows/add_assignee_to_pr.yml
  .github/workflows/my_setup_pr.yml
Labels: bug

#48 Use full changeset hash for 3rd-party GitHub Actions
  .github/workflows/add_assignee_to_pr.yml
  .github/workflows/my_test.yml
  .github/workflows/notify_slack_on_ci_failed.yml
  docs/adr/005-サードパーティのgithub-actionsのバージョンをfull-changeset-hashで固定する.md
  docs/adr/README.md
Labels: documentation
